# Generated by Django 5.2.1 on 2025-05-31 07:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('mobile', models.CharField(max_length=20, unique=True, verbose_name='Mobile')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='Nationality')),
                ('id_number', models.CharField(blank=True, max_length=50, verbose_name='ID Number')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=50, unique=True, verbose_name='Project Code')),
                ('name', models.CharField(max_length=200, verbose_name='Project Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('total_units', models.PositiveIntegerField(verbose_name='Total Units')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/', verbose_name='Image')),
                ('manager_name', models.CharField(max_length=150, verbose_name='Manager Name')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(max_length=50, unique=True, verbose_name='Service Code')),
                ('name', models.CharField(max_length=200, verbose_name='Service Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price Per Day (SAR)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Discount Amount (SAR)')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Discount Percentage (%)')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount Paid (SAR)')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card (Visa)'), ('transfer', 'Bank Transfer')], max_length=10, verbose_name='Payment Method')),
                ('booking_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Booking Datetime')),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='booked', max_length=10, verbose_name='Status')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.customer', verbose_name='Customer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.project', verbose_name='Project')),
            ],
        ),
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('price_at_booking', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price at Booking (SAR)')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.booking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.service')),
            ],
            options={
                'unique_together': {('booking', 'service')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='additional_services',
            field=models.ManyToManyField(blank=True, through='management.BookingService', to='management.service', verbose_name='Additional Services'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=50, unique=True, verbose_name='Unit Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='unit_images/', verbose_name='Image')),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied')], default='available', max_length=10, verbose_name='Status')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='management.project', verbose_name='Project')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.unit', verbose_name='Unit'),
        ),
    ]
