# Generated by Django 4.2.21 on 2025-06-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Price Per Day (SAR)'),
            preserve_default=False,
        ),
    ]
